#!/usr/bin/env python3
"""
gen_menus.py - Build-time codegen for Akashic Vault modules.

Scans every module's menu.json under src/modules/<kind>/<name>/ and emits C into
src/generated/:
  - <id>_params.h         : the TParamDesc[] table for one module
  - modules_table.cpp     : the CModuleRegistry table (id -> factory)

Modules are compiled into the kernel (no runtime JSON parsing). Humans edit
menu.json; this turns it into type-checked C. See docs/MODULE_FORMAT.md.

Usage:
  scripts/gen_menus.py --root .            # project root
"""

import argparse
import json
import os
import sys

KINDS = {"generator": "generators", "audiofx": "audiofx", "midifx": "midifx"}
PARAM_TYPE = {"int": "ParamType::Int", "float": "ParamType::Float",
              "enum": "ParamType::Enum", "bool": "ParamType::Bool"}
DISPLAY = {
    "raw": "ParamDisplay::Raw", "percent": "ParamDisplay::Percent",
    "db": "ParamDisplay::Decibels", "hz": "ParamDisplay::Hertz",
    "ms": "ParamDisplay::Milliseconds", "note": "ParamDisplay::Note",
    "semitones": "ParamDisplay::Semitones", "onoff": "ParamDisplay::OnOff",
}


def c_str(s):
    return '"' + str(s).replace('\\', '\\\\').replace('"', '\\"') + '"'


def find_modules(root):
    base = os.path.join(root, "src", "modules")
    found = []
    for kind_dir in KINDS.values():
        d = os.path.join(base, kind_dir)
        if not os.path.isdir(d):
            continue
        for name in sorted(os.listdir(d)):
            mj = os.path.join(d, name, "menu.json")
            if os.path.isfile(mj):
                found.append((kind_dir, name, mj))
    return found


def emit_params(mod, out_dir):
    mid = mod["id"]
    params = mod.get("params", [])
    lines = [
        "// AUTO-GENERATED from menu.json by scripts/gen_menus.py. DO NOT EDIT.",
        "#pragma once",
        '#include "../engine/tparamdesc.h"',
        "",
    ]
    for p in params:
        if p.get("type") == "enum":
            opts = p.get("options", [])
            lines.append(
                f"static const char *const k_{mid}_{p['id']}_opts[] = {{ "
                + ", ".join(c_str(o) for o in opts) + " };"
            )
    lines.append("")
    lines.append(f"static const TParamDesc k_{mid}_params[] = {{")
    for p in params:
        ptype = PARAM_TYPE[p.get("type", "int")]
        disp = DISPLAY.get(p.get("display", "raw"), "ParamDisplay::Raw")
        is_enum = p.get("type") == "enum"
        opts_ref = f"k_{mid}_{p['id']}_opts" if is_enum else "nullptr"
        nopts = len(p.get("options", [])) if is_enum else 0
        fmin = p.get("min", 0)
        fmax = p.get("max", (nopts - 1) if is_enum else 1)
        fdef = p.get("default", 0)
        fstep = p.get("step", 1)
        lines.append(
            f"  {{ {c_str(p['id'])}, {c_str(p.get('label', p['id']))}, "
            f"{ptype}, {disp}, "
            f"{float(fmin)}f, {float(fmax)}f, {float(fdef)}f, {float(fstep)}f, "
            f"{opts_ref}, {nopts} }},"
        )
    lines.append("};")
    lines.append(f"static const unsigned k_{mid}_param_count = "
                 f"sizeof(k_{mid}_params)/sizeof(k_{mid}_params[0]);")
    lines.append("")
    with open(os.path.join(out_dir, f"{mid}_params.h"), "w") as f:
        f.write("\n".join(lines))
    return len(params)


def emit_registry(mods, out_dir):
    lines = [
        "// AUTO-GENERATED by scripts/gen_menus.py. DO NOT EDIT.",
        '#include "../engine/cmoduleregistry.h"',
        "",
        "// Factory forward declarations: each module repo provides",
        "//   IModule *Create_<id>();",
    ]
    for m in mods:
        lines.append(f"extern IModule *Create_{m['id']} ();")
    kindmap = {"generators": "ModuleKind::Generator",
               "audiofx": "ModuleKind::AudioFX",
               "midifx": "ModuleKind::MidiFX"}
    if mods:
        lines += ["", "static const TModuleEntry s_entries[] = {"]
        for m in mods:
            lines.append(
                f"  {{ {c_str(m['id'])}, {c_str(m['name'])}, "
                f"{kindmap[m['kind_dir']]}, &Create_{m['id']} }},"
            )
        lines += [
            "};",
            "",
            "const TModuleEntry *CModuleRegistry::Entries () { return s_entries; }",
            "unsigned CModuleRegistry::Count () "
            "{ return sizeof(s_entries)/sizeof(s_entries[0]); }",
            "",
        ]
    else:
        # No modules yet (e.g. fresh Phase 0 checkout): emit a valid empty table.
        lines += [
            "",
            "const TModuleEntry *CModuleRegistry::Entries () { return nullptr; }",
            "unsigned CModuleRegistry::Count () { return 0; }",
            "",
        ]
    with open(os.path.join(out_dir, "modules_table.cpp"), "w") as f:
        f.write("\n".join(lines))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=".")
    args = ap.parse_args()

    out_dir = os.path.join(args.root, "src", "generated")
    os.makedirs(out_dir, exist_ok=True)

    mods = []
    for kind_dir, name, mj in find_modules(args.root):
        with open(mj) as f:
            data = json.load(f)
        data["kind_dir"] = kind_dir
        emit_params(data, out_dir)
        mods.append(data)
        print(f"  menu.json: {kind_dir}/{name} -> {data['id']} "
              f"({len(data.get('params', []))} params)")

    emit_registry(mods, out_dir)
    print(f"gen_menus: {len(mods)} module(s) -> {out_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
